version: "3.8"

services:
  # Nosso App de IA
  app:
    build: .
    container_name: app-ia
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db # O app só sobe depois que o banco estiver pronto

  # Nosso Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: db-postgres
    restart: always
    env_file:
      - .env # O Docker vai ler as variáveis daqui
    ports:
      - "5432:5432"

  # Interface para ver o Banco de Dados (Opcional, mas muito útil)
  adminer:
    image: adminer
    container_name: db-adminer
    restart: always
    ports:
      - "8080:8080"
